
trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'
  
steps:
- bash: dotnet build --configuration $(buildConfiguration)
  displayName:'dotnet build $(buildConfiguration)'
